import type { TransactionInput } from './api/types'

export interface Preset {
  id: string
  label: string
  description: string
  tx: TransactionInput
}

// Seeds match backend/app/agent/feature_store.py::seed_demo so the agent's tools
// return meaningful history for card_good_001 / card_ato_002.
export const PRESETS: Preset[] = [
  {
    id: 'legit',
    label: 'Legit: routine purchase',
    description: 'Known card, known device, typical amount, consistent email and region.',
    tx: {
      card_id: 'card_good_001',
      amount: 62.5,
      product_code: 'W',
      card_network: 'visa',
      card_type: 'debit',
      purchaser_email_domain: 'gmail.com',
      billing_region: '315',
      billing_country: '87',
      distance_billing_to_purchase: 3,
      timestamp_delta_seconds: 86400 * 10 + 14 * 3600,
      device_type: 'mobile',
      device_info: 'iOS Device',
      card_txn_count: 14,
      email_txn_count: 14,
      device_txn_count: 12,
      days_since_prev_txn: 6,
      days_since_card_first_seen: 410,
      days_since_device_first_seen: 380,
      card_avg_amount: 58,
      card_known_devices: ['iOS Device'],
    },
  },
  {
    id: 'ambiguous',
    label: 'Ambiguous: new device, larger amount',
    description: 'Established card but first purchase from a new device at 3x the usual amount.',
    tx: {
      card_id: 'card_ato_002',
      amount: 189.99,
      product_code: 'C',
      card_network: 'mastercard',
      card_type: 'credit',
      purchaser_email_domain: 'outlook.com',
      billing_region: '204',
      billing_country: '87',
      distance_billing_to_purchase: 45,
      timestamp_delta_seconds: 86400 * 12 + 21 * 3600,
      device_type: 'mobile',
      device_info: 'SM-G960U Build/R16NW',
      card_txn_count: 9,
      email_txn_count: 9,
      device_txn_count: 1,
      days_since_prev_txn: 11,
      days_since_card_first_seen: 300,
      days_since_device_first_seen: 0,
      card_avg_amount: 38,
      card_known_devices: ['Windows'],
    },
  },
  {
    id: 'stolen',
    label: 'Fraud: stolen card pattern',
    description: 'Brand-new card and device, disposable recipient email, far from billing, night-time.',
    tx: {
      card_id: 'card_new_777',
      amount: 1250,
      product_code: 'W',
      card_network: 'visa',
      card_type: 'credit',
      purchaser_email_domain: 'gmail.com',
      recipient_email_domain: 'mailinator.com',
      billing_region: '126',
      billing_country: '87',
      distance_billing_to_purchase: 812,
      timestamp_delta_seconds: 86400 * 3 + 3 * 3600,
      device_type: 'mobile',
      device_info: 'SM-G9650 Build/R16NW',
      card_txn_count: 1,
      email_txn_count: 1,
      device_txn_count: 1,
      days_since_prev_txn: 0,
      days_since_card_first_seen: 0,
      days_since_device_first_seen: 0,
    },
  },
  {
    id: 'testing',
    label: 'Fraud: card testing',
    description: 'Micro amount repeated within a day on a brand-new card.',
    tx: {
      card_id: 'card_new_778',
      amount: 1.0,
      product_code: 'C',
      card_network: 'visa',
      card_type: 'debit',
      purchaser_email_domain: 'yopmail.com',
      timestamp_delta_seconds: 86400 * 5 + 4 * 3600,
      device_type: 'desktop',
      device_info: 'Windows',
      card_txn_count: 6,
      days_since_prev_txn: 0,
      days_since_card_first_seen: 0,
      days_since_prev_txn_same_amount: 0,
      days_since_device_first_seen: 0,
    },
  },
]
