import type { TransactionInput } from './api/types'

export interface Preset {
  id: string
  label: string
  description: string
  tx: TransactionInput
}

// Seeds match backend/app/agent/feature_store.py::seed_demo so live scoring
// computes card history for these card_ids. Device IDs are synthetic enrolled
// identities; all device_info values remain descriptions.
export const PRESETS: Preset[] = [
  {
    id: 'legit',
    label: 'Legit: routine purchase',
    description: 'Known card, known device, typical amount, consistent email and region.',
    tx: {
      card_id: 'card_good_001',
      amount: 62.5,
      card_network: 'visa',
      card_type: 'debit',
      purchaser_email_domain: 'gmail.com',
      billing_region: '315',
      billing_country: '87',
      dist1: 3,
      timestamp_delta_seconds: 86400 * 10 + 14 * 3600,
      device_type: 'mobile',
      device_info: 'SM-G950F Build/R16NW',
      device_id: 'demo:device:good-001',
    },
  },
  {
    id: 'ambiguous',
    label: 'Ambiguous: unknown device, larger amount',
    description: 'Established card with unknown device identity at roughly 5x the usual amount.',
    tx: {
      card_id: 'card_ato_002',
      amount: 189.99,
      card_network: 'mastercard',
      card_type: 'credit',
      purchaser_email_domain: 'outlook.com',
      billing_region: '204',
      billing_country: '87',
      dist1: 45,
      timestamp_delta_seconds: 86400 * 12 + 21 * 3600,
      device_type: 'mobile',
      device_info: 'SM-G960U Build/R16NW',
    },
  },
  {
    id: 'stolen',
    label: 'Fraud: stolen card pattern',
    description: 'Brand-new card, device shared across many cards, disposable recipient email, large dist1, night-time.',
    tx: {
      card_id: 'card_new_777',
      amount: 1250,
      card_network: 'visa',
      card_type: 'credit',
      purchaser_email_domain: 'gmail.com',
      recipient_email_domain: 'mailinator.com',
      billing_region: '126',
      billing_country: '87',
      dist1: 812,
      timestamp_delta_seconds: 86400 * 3 + 3 * 3600,
      device_type: 'mobile',
      device_info: 'SM-G9650 Build/R16NW',
      device_id: 'demo:device:shared-001',
    },
  },
  {
    id: 'testing',
    label: 'Fraud: card testing',
    description: 'Micro amount on a brand-new card (no store history).',
    tx: {
      card_id: 'card_new_778',
      amount: 1.0,
      card_network: 'visa',
      card_type: 'debit',
      purchaser_email_domain: 'yopmail.com',
      timestamp_delta_seconds: 86400 * 5 + 4 * 3600,
      device_type: 'desktop',
      device_info: 'Windows',
    },
  },
  {
    id: 'swipe_legit',
    label: 'Card-present: grocery swipe',
    description:
      'Magstripe swipe at a known US grocer, PIN verified, track CVV matches, amount inside the limit. Jev sees card_present.rules all clear.',
    tx: {
      card_id: 'card_swipe_001',
      amount: 52,
      channel: 'card_present',
      entry_mode: 'swipe',
      card_status: 'open',
      card_network: 'visa',
      card_type: 'credit',
      cvm_result: 'pin_verified',
      pin_tries_exceeded: false,
      track_cvv: 'match',
      merchant_id: 'merch_grocery_88',
      merchant_name: 'Market Street',
      mcc: '5411',
      merchant_country: 'US',
      merchant_city: 'Austin',
      cardholder_country: 'US',
      terminal_attended: true,
      available_credit_usd: 5000,
      single_purchase_limit_usd: 2000,
    },
  },
  {
    id: 'swipe_fallback',
    label: 'Card-present: fallback swipe abroad',
    description:
      'Chip fell back to magstripe, signature instead of PIN, merchant country changed inside 2 hours, and the amount is several times the card prior mean. No hard control fired — Jev decides from card_present.rules, including the amount.',
    tx: {
      card_id: 'card_swipe_001',
      amount: 420,
      channel: 'card_present',
      entry_mode: 'fallback_swipe',
      card_status: 'open',
      card_network: 'visa',
      card_type: 'credit',
      cvm_result: 'signature',
      pin_tries_exceeded: false,
      track_cvv: 'match',
      merchant_id: 'merch_elec_19',
      merchant_name: 'Centro Eletronicos',
      mcc: '5732',
      merchant_country: 'BR',
      merchant_city: 'Sao Paulo',
      cardholder_country: 'US',
      terminal_attended: true,
      available_credit_usd: 5000,
      single_purchase_limit_usd: 2000,
    },
  },
  {
    id: 'swipe_stolen',
    label: 'Card-present: stolen card',
    description:
      'Card status is stolen. The issuer control declines before the model is called.',
    tx: {
      card_id: 'card_swipe_001',
      amount: 48,
      channel: 'card_present',
      entry_mode: 'swipe',
      card_status: 'stolen',
      card_network: 'visa',
      card_type: 'credit',
      cvm_result: 'signature',
      track_cvv: 'mismatch',
      merchant_id: 'merch_elec_19',
      merchant_name: 'Quick Electronics',
      mcc: '5732',
      merchant_country: 'US',
      merchant_city: 'Dallas',
      cardholder_country: 'US',
      terminal_attended: true,
      available_credit_usd: 5000,
      single_purchase_limit_usd: 2000,
    },
  },
]